/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oop_template;



import java.awt.Image;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTextField;





/**
 *
 * @author Jackh
 */
public class Search_Employee extends javax.swing.JFrame {

    /**
     * Creates new form Search_Employee
     * @author Jack Holmes (50053641)
     */
    public Search_Employee() {
        initComponents();
            // Used to load the image from the images directory within the project
           ImageIcon icon = new ImageIcon(getClass().getResource("/images/RJFMotorsLogo.jpeg"));
            //Gets the image 
           Image img = icon.getImage();
           //Used to scale the image to fit within the label
            Image imgScale = img.getScaledInstance(lblLogoImage.getWidth(), lblLogoImage.getHeight(), Image.SCALE_SMOOTH);
            //creates a new image with the new scale
            ImageIcon scaledIcon = new ImageIcon(imgScale);
            //sets the scaled image within the label
            lblLogoImage.setIcon(scaledIcon);



    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLogoImage = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        pnlEmployeeSearch = new javax.swing.JPanel();
        lblEmployeeID = new javax.swing.JLabel();
        txtEmployeeID = new javax.swing.JTextField();
        btnEmployeeSearch = new javax.swing.JButton();
        btnEmpMenu = new javax.swing.JButton();
        btnAddNewEmp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lblLogoImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/RJFMotorsLogo.jpeg"))); // NOI18N
        lblLogoImage.setToolTipText("");

        lblTitle.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        lblTitle.setText("RJA Motors");

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        pnlEmployeeSearch.setBackground(new java.awt.Color(153, 255, 255));
        pnlEmployeeSearch.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lblEmployeeID.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEmployeeID.setText("Employee ID:");

        txtEmployeeID.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtEmployeeID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmployeeIDActionPerformed(evt);
            }
        });

        btnEmployeeSearch.setBackground(new java.awt.Color(0, 0, 0));
        btnEmployeeSearch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEmployeeSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnEmployeeSearch.setText("Search");
        btnEmployeeSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmployeeSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlEmployeeSearchLayout = new javax.swing.GroupLayout(pnlEmployeeSearch);
        pnlEmployeeSearch.setLayout(pnlEmployeeSearchLayout);
        pnlEmployeeSearchLayout.setHorizontalGroup(
            pnlEmployeeSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEmployeeSearchLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(pnlEmployeeSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnEmployeeSearch)
                    .addGroup(pnlEmployeeSearchLayout.createSequentialGroup()
                        .addComponent(lblEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(136, Short.MAX_VALUE))
        );
        pnlEmployeeSearchLayout.setVerticalGroup(
            pnlEmployeeSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEmployeeSearchLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(pnlEmployeeSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(btnEmployeeSearch)
                .addGap(27, 27, 27))
        );

        btnEmpMenu.setBackground(new java.awt.Color(0, 0, 0));
        btnEmpMenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEmpMenu.setForeground(new java.awt.Color(255, 255, 255));
        btnEmpMenu.setText("Return Menu");
        btnEmpMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpMenuActionPerformed(evt);
            }
        });

        btnAddNewEmp.setBackground(new java.awt.Color(0, 0, 0));
        btnAddNewEmp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddNewEmp.setForeground(new java.awt.Color(255, 255, 255));
        btnAddNewEmp.setText("Add New");
        btnAddNewEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewEmpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlEmployeeSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAddNewEmp)
                        .addGap(18, 18, 18)
                        .addComponent(btnEmpMenu)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(90, Short.MAX_VALUE)
                .addComponent(pnlEmployeeSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEmpMenu)
                    .addComponent(btnAddNewEmp))
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitle)
                .addGap(49, 49, 49)
                .addComponent(lblLogoImage, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblLogoImage, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmployeeIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmployeeIDActionPerformed
   
    }//GEN-LAST:event_txtEmployeeIDActionPerformed

    
    
     /**
     * This is the return to the employee main menu button, this redirects the user to the employee main menu.
     * @author Jack Holmes (50053641)
     */
    
    private void btnEmpMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpMenuActionPerformed
        Employee_Main_Menu employeeMenu = new Employee_Main_Menu();
        // Makes the Employee_Main_Menu frame visible
        
        employeeMenu.setVisible(true);
        // Makes the current frame invisible if needed
        
        this.setVisible(false);
    }//GEN-LAST:event_btnEmpMenuActionPerformed

     /**
     * This is the employee search button, this searches for the employee ID in the employee data text file.
     * @author Jack Holmes (50053641)
     */
    private void btnEmployeeSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmployeeSearchActionPerformed
        String employeeIDText = txtEmployeeID.getText().trim();
    if (employeeIDText.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Please enter an employee ID.");
        return;
    }

    if (!employeeIDText.matches("\\d+")) {
        JOptionPane.showMessageDialog(null, "Please enter a valid employee ID.");
        return;
    }

    int employeeID = Integer.parseInt(employeeIDText);
    Employee_Details foundEmployee = null;

    try {
        // Open the employee data file for reading
        BufferedReader reader = new BufferedReader(new FileReader("storage/employee_data.txt"));

        // Read the file line by line
        String line;
        while ((line = reader.readLine()) != null) {
            // Split the line into fields separated by commas
            String[] fields = line.split(",");

            // Parse the employee ID from the first field
            int id = Integer.parseInt(fields[0]);

            // Check if the ID matches the one the user is looking for
            if (id == employeeID) {
                // Create a new Employee_Details object and set its properties from the fields in the line
                foundEmployee = new Employee_Details();
                foundEmployee.setEmployeeID(id);
                foundEmployee.setTitle(fields[1]);
                foundEmployee.setForename(fields[2]);
                foundEmployee.setSurname(fields[3]);
                foundEmployee.setGender(fields[4]);
                foundEmployee.setJobTitle(fields[5]);
                foundEmployee.setContractedHours(Integer.parseInt(fields[6]));
                foundEmployee.setHourlyRate(Integer.parseInt(fields[7]));

                // stop the cpde
                break;
            }
        }

        // Close the file
        reader.close();
    } catch (IOException e) {
        // Handle any errors that occur while reading the file
        JOptionPane.showMessageDialog(null, "Error reading employee data file: " + e.getMessage());
        return;
    }

    if (foundEmployee == null) {
        JOptionPane.showMessageDialog(null, "Employee not found. Please enter an existing ID.");
    } else {
        // Open the Modify_Employee frame with the found employee's details
        this.dispose();
        Modify_Employee modifyEmployee = new Modify_Employee();
        modifyEmployee.setEmployeeDetails(foundEmployee);
        modifyEmployee.setVisible(true);
    }
    }//GEN-LAST:event_btnEmployeeSearchActionPerformed

     /**
     * This is the add new button, this button redirects the user to the modify employee page.
     * @author Jack Holmes (50053641)
     */
    private void btnAddNewEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewEmpActionPerformed
        Modify_Employee modifyEmployee = new Modify_Employee();
        
        modifyEmployee.setVisible(true);
    }//GEN-LAST:event_btnAddNewEmpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Search_Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Search_Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Search_Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Search_Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Search_Employee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNewEmp;
    private javax.swing.JButton btnEmpMenu;
    private javax.swing.JButton btnEmployeeSearch;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblEmployeeID;
    private javax.swing.JLabel lblLogoImage;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlEmployeeSearch;
    private javax.swing.JTextField txtEmployeeID;
    // End of variables declaration//GEN-END:variables
}
