/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oop_template;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.swing.JOptionPane;

/**
 * Create public class Search_Customer
 * @author anastasiaridge 50017135
 */
public class Search_Customer extends javax.swing.JFrame {

    //create boolean for validation
    private boolean isCustomerIDValid = false;

    /**
     * Creates new form Search_Customer
     * @author  Ana Ridge (50017135)
     */
    public Search_Customer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblLogoImage = new javax.swing.JLabel();
        pnlCustomerSearch = new javax.swing.JPanel();
        lblCustomerID = new javax.swing.JLabel();
        txtCustomerID = new javax.swing.JTextField();
        btnCustomerSearch = new javax.swing.JButton();
        lblCustomerIDCheck = new javax.swing.JLabel();
        btnEmpMenu = new javax.swing.JButton();
        btnModifyCust = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        lblTitle.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        lblTitle.setText("RJA Motors");

        lblLogoImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/RJFMotorsLogo.jpeg"))); // NOI18N
        lblLogoImage.setText("(logo)");

        pnlCustomerSearch.setBackground(new java.awt.Color(153, 255, 255));
        pnlCustomerSearch.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 14))); // NOI18N

        lblCustomerID.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblCustomerID.setText("Customer ID:");

        txtCustomerID.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtCustomerID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCustomerIDKeyReleased(evt);
            }
        });

        btnCustomerSearch.setBackground(new java.awt.Color(0, 0, 0));
        btnCustomerSearch.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnCustomerSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnCustomerSearch.setText("Search");
        btnCustomerSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomerSearchActionPerformed(evt);
            }
        });

        lblCustomerIDCheck.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        lblCustomerIDCheck.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout pnlCustomerSearchLayout = new javax.swing.GroupLayout(pnlCustomerSearch);
        pnlCustomerSearch.setLayout(pnlCustomerSearchLayout);
        pnlCustomerSearchLayout.setHorizontalGroup(
            pnlCustomerSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCustomerSearchLayout.createSequentialGroup()
                .addGroup(pnlCustomerSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlCustomerSearchLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblCustomerIDCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlCustomerSearchLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(lblCustomerID, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
                        .addGroup(pnlCustomerSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtCustomerID, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCustomerSearch))))
                .addGap(27, 27, 27))
        );
        pnlCustomerSearchLayout.setVerticalGroup(
            pnlCustomerSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCustomerSearchLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(pnlCustomerSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCustomerID)
                    .addComponent(txtCustomerID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCustomerIDCheck)
                .addGap(12, 12, 12)
                .addComponent(btnCustomerSearch)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        btnEmpMenu.setBackground(new java.awt.Color(0, 0, 0));
        btnEmpMenu.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        btnEmpMenu.setForeground(new java.awt.Color(255, 255, 255));
        btnEmpMenu.setText("⬅");
        btnEmpMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpMenuActionPerformed(evt);
            }
        });

        btnModifyCust.setBackground(new java.awt.Color(0, 0, 0));
        btnModifyCust.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnModifyCust.setForeground(new java.awt.Color(255, 255, 255));
        btnModifyCust.setText("Add New");
        btnModifyCust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyCustActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTitle)
                        .addGap(73, 73, 73)
                        .addComponent(lblLogoImage, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlCustomerSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnEmpMenu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnModifyCust)
                        .addGap(33, 33, 33)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitle)
                    .addComponent(lblLogoImage, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(pnlCustomerSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEmpMenu)
                    .addComponent(btnModifyCust))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Button to return to the Employee Main Menu
     * @param evt 
     * @author  Ana Ridge (50017135)
     */
    private void btnEmpMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpMenuActionPerformed
        //need to add check for logged in
        this.dispose();
        new Employee_Main_Menu().setVisible(true);
    }//GEN-LAST:event_btnEmpMenuActionPerformed

    /**
     * Validation for the Customer ID field
     * @param evt 
     * @author  Ana Ridge (50017135)
     */
    private void txtCustomerIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCustomerIDKeyReleased
        //input validation: only allow for numbers
        String text = txtCustomerID.getText();
        Boolean isOnlyNumbers = text.matches("^[0-9]*$");
        if (text.isBlank()) {
            isCustomerIDValid = false;
            lblCustomerIDCheck.setText("Please enter a value (numbers).");
        } else if (isOnlyNumbers) {
            lblCustomerIDCheck.setText("");
            isCustomerIDValid = true;
        } else {
            lblCustomerIDCheck.setText("Please enter only numbers.");
            isCustomerIDValid = false;
        }
    }//GEN-LAST:event_txtCustomerIDKeyReleased

    /**
     * Method to Search for matching Customer ID in text file
     * @param evt 
     * @author  Ana Ridge (50017135)
     */
    private void btnCustomerSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomerSearchActionPerformed
        // set this to an empty customer because if no customer is found, we won't have done a search
        appData.Customer_Details = new Customer_Details();
        appData.loadAllCustomerDetails();

        Customer_Details foundCustomer = null;
        for (Customer_Details customer : appData.allCustomerDetails) {
            String customerID = String.valueOf(customer.getCustomerID());
            if (customerID.equals(txtCustomerID.getText())) {
                foundCustomer = customer;
                break;
            }
        }
        if (foundCustomer == null) {
            //show error message
            JOptionPane.showMessageDialog(null, "Customer ID not found. Please enter an existing ID.");
        } else {
            this.dispose();
            appData.Customer_Details = foundCustomer;
            Modify_Customer modifyCustomer = new Modify_Customer();
            modifyCustomer.setAllValid();
            modifyCustomer.setVisible(true);
        }

    }//GEN-LAST:event_btnCustomerSearchActionPerformed

    /**
     * Button to call the selected customer's details and open Modify Customer form
     * @param evt 
     * @author  Ana Ridge (50017135)
     */
    private void btnModifyCustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyCustActionPerformed
        // 'add new' open modify customer page
        this.dispose();
        Modify_Customer modifyCustomer = new Modify_Customer();
        appData.Customer_Details = new Customer_Details();
        modifyCustomer.setAllValid();
        modifyCustomer.setVisible(true);
    }//GEN-LAST:event_btnModifyCustActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Search_Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Search_Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Search_Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Search_Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Search_Customer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCustomerSearch;
    private javax.swing.JButton btnEmpMenu;
    private javax.swing.JButton btnModifyCust;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCustomerID;
    private javax.swing.JLabel lblCustomerIDCheck;
    private javax.swing.JLabel lblLogoImage;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlCustomerSearch;
    private javax.swing.JTextField txtCustomerID;
    // End of variables declaration//GEN-END:variables
}
