/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oop_template;

import javax.swing.*;
import java.io.*;
import java.nio.file.Files;
import java.nio.file.Paths;

/**
 *
 * @Roy Ferguson(50004216)
 */
public class View_Car_Sold extends javax.swing.JFrame {
    private javax.swing.DefaultListModel listCars;


    /**
     * Creates new form View_Car
     * @Roy Ferguson(50004216)
     */
    public View_Car_Sold() {
        initComponents();
        // Setting the screen position to center
        setLocationRelativeTo(null);

        // Creating a list so that you are able to add data to list and view the car details.
        listCars = new javax.swing.DefaultListModel();

        // Variables used to read lines in text file (Cars_Sold.txt)
        String eachLine;
        int numberLinesFile = 0;
        int numberLines = 1;

        // Making sure that the Cars_Sold.txt file exists.
        try {
            File carTextFile = new File("storage/Cars_Sold.txt");
            if (carTextFile.createNewFile()) {
                System.out.println("File Created" + carTextFile.getName());
                JOptionPane.showMessageDialog(null, "The Text File created is: " + carTextFile, "Text File Created?",JOptionPane.PLAIN_MESSAGE);
            } else {
                System.out.println("File aleardy exists");
                JOptionPane.showMessageDialog(null, "Text File: " + carTextFile + " already exists?", "Text File Already Exists?",JOptionPane.PLAIN_MESSAGE);
            }

            // Creating a file reader and a buffer reader to read each line in text file.
            FileReader fr = null;
            try {
                fr = new FileReader("storage/Cars_Sold.txt");
            } catch (FileNotFoundException e) {
                throw new RuntimeException(e);
            }
            BufferedReader line = new BufferedReader(fr);
            while(true) {
                try {
                    if (!((eachLine=line.readLine())!=null)) break;
                } catch (IOException e) {
                    throw new RuntimeException(e);
                }
                // Counting the number of lines in the text file
                numberLinesFile++;
            }

            // Reading each line in text file due to the total number of lines in the file gotten from (numberLinesFile).
            // Adding each line of data to the list.
            for(int i = 0; i < numberLinesFile; i++){
                String line32 = null;
                try {
                    line32 = Files.readAllLines(Paths.get("storage/Cars_Sold.txt")).get((numberLines-1));
                    listCars.addElement(line32);
                } catch (IOException e) {
                    throw new RuntimeException(e);
                }
                // Adding one in order to read the next line in text file
                numberLines++;
            }
            // Setting the jList with all the data added to the car list
            lstCarDetails.setModel(listCars);

        } catch (IOException e) {
            System.out.println("An error occurred");
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstCarDetails = new javax.swing.JList<>();
        lblViewCarsTitle = new javax.swing.JLabel();
        btnEmpMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jScrollPane1.setViewportView(lstCarDetails);

        lblViewCarsTitle.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        lblViewCarsTitle.setText("Motors Bought");

        btnEmpMenu.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        btnEmpMenu.setText("⬅");
        btnEmpMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(btnEmpMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(71, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblViewCarsTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(166, 166, 166))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(lblViewCarsTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEmpMenu)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Employee Menu Button to take you back to Employee Main Menu
     * @author Roy Ferguson(50004216)
     */
    private void btnEmpMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpMenuActionPerformed
        
        //close view cars sold and open Employee Main Menu
        this.dispose();
        new Employee_Main_Menu().setVisible(true);
    }//GEN-LAST:event_btnEmpMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View_Car_Sold.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View_Car_Sold.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View_Car_Sold.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View_Car_Sold.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View_Car_Sold().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEmpMenu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblViewCarsTitle;
    private javax.swing.JList<String> lstCarDetails;
    // End of variables declaration//GEN-END:variables
}
