/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oop_template;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.DefaultListModel;

/**
 *
 * @author anastasiaridge
 */
public class View_Customer extends javax.swing.JFrame {

    //declare customerList variable to be read later
    DefaultListModel<Customer_Details> customerList;
    
    
    public View_Customer() {
        initComponents();
        customerList = new DefaultListModel<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        lstCustomer = new javax.swing.JList<>();
        lblViewCustomer = new javax.swing.JLabel();
        btnLoadCustomerDetails = new javax.swing.JButton();
        btnReturnEmpMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lstCustomer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lstCustomer.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jScrollPane2.setViewportView(lstCustomer);
        lstCustomer.getAccessibleContext().setAccessibleParent(lstCustomer);

        lblViewCustomer.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblViewCustomer.setText("Customer Details:");

        btnLoadCustomerDetails.setFont(new java.awt.Font("Helvetica Neue", 2, 14)); // NOI18N
        btnLoadCustomerDetails.setText("Load Customer Details");
        btnLoadCustomerDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadCustomerDetailsActionPerformed(evt);
            }
        });

        btnReturnEmpMenu.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        btnReturnEmpMenu.setText("⬅");
        btnReturnEmpMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnEmpMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblViewCustomer)
                    .addComponent(btnLoadCustomerDetails)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnReturnEmpMenu, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblViewCustomer)
                .addGap(12, 12, 12)
                .addComponent(btnLoadCustomerDetails)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnReturnEmpMenu)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoadCustomerDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadCustomerDetailsActionPerformed
        /* declaring variable
           load data from customer details text file
        */
        BufferedReader reader;
        //clearing the list so that duplicate data doesn't occur
        customerList.clear();
        try{
            //load the file
            reader = new BufferedReader (new FileReader("storage/Customer_Details.txt"));
            
            String currentLine = "";
            
            //https://stackoverflow.com/questions/62614024/how-to-implement-hasnext-method-with-bufferedreader-stringtokenizer
            
            //iterate through file line by line using while loop until last line which will be null, loop stops
            while((currentLine = reader.readLine()) != null){
                
                String[] customerParts = currentLine.split(",");
                
                Customer_Details customer = new Customer_Details();
                customer.setCustomerID(Integer.parseInt(customerParts[0]));
                customer.setCustomerTitle(customerParts[1]);
                customer.setCustomerForename(customerParts[2]);
                customer.setCustomerSurname(customerParts[3]);
                customer.setCustomerGender(customerParts[4]);
                customer.setCustomerMobile(customerParts[5]);
                customer.setCustomerAddress(customerParts[6]);
                
                
                customerList.addElement(customer);
            }
            lstCustomer.setModel(customerList);
        }
        //if error occurs, nothing will print
        catch(IOException e){
            System.out.println("");
        }
    }//GEN-LAST:event_btnLoadCustomerDetailsActionPerformed

    private void btnReturnEmpMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnEmpMenuActionPerformed
        //return to employee enu, close view customer
        this.dispose();
        new Employee_Main_Menu().setVisible(true);
             
    }//GEN-LAST:event_btnReturnEmpMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View_Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View_Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View_Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View_Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View_Customer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLoadCustomerDetails;
    private javax.swing.JButton btnReturnEmpMenu;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblViewCustomer;
    private javax.swing.JList<Customer_Details> lstCustomer;
    // End of variables declaration//GEN-END:variables
}
