/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oop_template;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Jackh
 */
public class View_Employee extends javax.swing.JFrame {
    //declare customerList variable to be read later
    DefaultListModel<Employee_Details> employeeList;
    
    /**
     * Creates new form View_Employee
     */
    public View_Employee() {
        initComponents();
        employeeList = new DefaultListModel<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblEmployeeList = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstEmployee = new javax.swing.JList<>();
        btnEmpReturnMenu = new javax.swing.JButton();
        btnLoadEmpDetails = new javax.swing.JButton();
        btnEditEmployee = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        lblEmployeeList.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        lblEmployeeList.setText("Employee Details:");

        lstEmployee.setBackground(new java.awt.Color(153, 255, 255));
        lstEmployee.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        lstEmployee.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jScrollPane1.setViewportView(lstEmployee);
        lstEmployee.getAccessibleContext().setAccessibleParent(lstEmployee);

        btnEmpReturnMenu.setBackground(new java.awt.Color(0, 0, 0));
        btnEmpReturnMenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEmpReturnMenu.setForeground(new java.awt.Color(255, 255, 255));
        btnEmpReturnMenu.setText("Return Menu");
        btnEmpReturnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpReturnMenuActionPerformed(evt);
            }
        });

        btnLoadEmpDetails.setBackground(new java.awt.Color(0, 0, 0));
        btnLoadEmpDetails.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLoadEmpDetails.setForeground(new java.awt.Color(255, 255, 255));
        btnLoadEmpDetails.setText("Load Employee Details");
        btnLoadEmpDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadEmpDetailsActionPerformed(evt);
            }
        });

        btnEditEmployee.setBackground(new java.awt.Color(0, 0, 0));
        btnEditEmployee.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEditEmployee.setForeground(new java.awt.Color(255, 255, 255));
        btnEditEmployee.setText("Edit Employee");
        btnEditEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditEmployeeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(btnEmpReturnMenu)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEditEmployee))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblEmployeeList)
                                .addGap(121, 121, 121))))
                    .addComponent(btnLoadEmpDetails))
                .addGap(34, 34, 34))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblEmployeeList, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLoadEmpDetails)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEmpReturnMenu)
                    .addComponent(btnEditEmployee))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEmpReturnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpReturnMenuActionPerformed
        Employee_Main_Menu employeeMenu = new Employee_Main_Menu();
        // Makes the View_Employee frame visible
        
        employeeMenu.setVisible(true);
        // Makes the current frame invisible if needed
        
        this.setVisible(false);
    }//GEN-LAST:event_btnEmpReturnMenuActionPerformed

    private void btnLoadEmpDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadEmpDetailsActionPerformed
        /* declaring variable
           load data from customer details text file
        */
        BufferedReader reader;
        //clearing the list so that duplicate data doesn't occur
        employeeList.clear();
        try{
            //load the file
            reader = new BufferedReader (new FileReader("storage/employee_data.txt"));
            
            String currentLine = "";
            
            //https://stackoverflow.com/questions/62614024/how-to-implement-hasnext-method-with-bufferedreader-stringtokenizer
            
            //iterate through file line by line using while loop until last line which will be null, loop stops
            while((currentLine = reader.readLine()) != null){
                
                String[] employeeParts = currentLine.split(",");
                
                Employee_Details employee = new Employee_Details();
                employee.setEmployeeID(Integer.parseInt(employeeParts[0]));
                employee.setTitle(employeeParts[1]);
                employee.setForename(employeeParts[2]);
                employee.setSurname(employeeParts[3]);
                employee.setGender(employeeParts[4]);
                employee.setJobTitle(employeeParts[5]);
                employee.setContractedHours(Integer.parseInt(employeeParts[6]));
                employee.setHourlyRate(Integer.parseInt(employeeParts[7]));
                
                
                employeeList.addElement(employee);
            }
            lstEmployee.setModel(employeeList);
        }
        //if error occurs, nothing will print
        catch(IOException e){
            System.out.println("");
        }
    }//GEN-LAST:event_btnLoadEmpDetailsActionPerformed

    private void btnEditEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditEmployeeActionPerformed
    if (lstEmployee.getSelectedValue() != null) {
         appData.Employee_Details = lstEmployee.getSelectedValue();
         this.dispose();
         Modify_Employee modifyEmployeeForm = new Modify_Employee();
         modifyEmployeeForm.setEmployeeDetails(appData.Employee_Details);
         modifyEmployeeForm.setVisible(true);
     } else {
         JOptionPane.showMessageDialog(null, "Please select an employee before continuing.", "Error", JOptionPane.PLAIN_MESSAGE);
     }
    }//GEN-LAST:event_btnEditEmployeeActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View_Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View_Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View_Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View_Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View_Employee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditEmployee;
    private javax.swing.JButton btnEmpReturnMenu;
    private javax.swing.JButton btnLoadEmpDetails;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEmployeeList;
    private javax.swing.JList<Employee_Details> lstEmployee;
    // End of variables declaration//GEN-END:variables
}
